### PR TITLE
Report video button

### PR DESCRIPTION
**Pull request by milan-lakhani**
Backend: New Schema Created - ReportForm
Backend: New route added /forms/report

Frontend: New Component created in component/Misc - ReportButton.jsx
Frontend: reportButton Added to All Game Pages.
Frontend: handled reponse from backend Success/Error in frontend

### CODE REVIEW

**Comment by Chris5613** [comment]
@milan-lakhani The report button looks very nice, what I would suggest is for the modal make it a pop-up instead of what you did so it doesn't push the video down or you don't really need to ask for confirmation, you can make it so the moment the user clicks it the report will send and if you're gonna do this then at the end add an alert() telling them thank you for reporting. 

I also recommend deleting all the comments.

**Comment by milan-lakhani** [comment]
Okay @Chris5613 Sounds good

**Comment by milan-lakhani** [comment]
@Chris5613 Made the necessary changes. Should I keep the PR or create a new one?

**Comment by Chris5613** [comment]
You can keep the PR. it autmatically updates when you push.

Last thing is to change

```javascript 
const response = await fetch('http://localhost:3001/form/report')
```
to
```javascript 
const response = await fetch('https://rr-back-end.onrender.com/form/report')
```

after that I'll make the merge!

**Review by Chris5613 — APPROVED** [review]
Everything looks good!

**Pull request merged**
