### PR TITLE
Responding to Issue on video being too big on mobile published by Chris5613

### PR DESCRIPTION
**Pull request by hyohyo814**
Removed minimum size limitations in CSS and adapted wrapper to be responsive to window size below 768px.

### CODE REVIEW

**Comment by Chris5613** [comment]
@hyohyo814 You might have to redo it. It looks good on small screens but if you're looking at it on a bigger screen , the video is taking up the whole page. 

3d775082b2e0c5015c1f4132bd8071c3

**Comment by hyohyo814** [comment]
My apologies, I might have missed some constraints when I transferred the code from VS. Thank you for pointing it out.

**Comment by hyohyo814** [comment]
image
I am unsure of if I am running the development incorrectly, but this is what I see on a large screen running on localhost. I apologize for the inconvenience, I am still trying to familiarize myself with everything.

**Comment by Chris5613** [comment]
hmmm that's weird. I'll approve the merge and we can test it, if anything we can propose new changes.

**Review by Chris5613 — APPROVED** [review]

**Pull request merged**
