### PR TITLE
SEO stuff

### PR DESCRIPTION
**Pull request by HIMANSHIKSHARMA**
changes

### CODE REVIEW

**Comment by Chris5613** [comment]
@HIMANSHIKSHARMA Hi , May I ask what changes are you trying to merge?

**Comment by Chris5613** [comment]
Closing this request as this merge request does not benefit or do anything.

**Comment by HIMANSHIKSHARMA** [comment]
I was trying to solve the issue but I see someone has already done that.
I'll delete my pull request from there, I'm new to open source so I didn't
notice it.

**Comment by Chris5613** [comment]
@HIMANSHIKSHARMA That's okay! , next time if you want to work on an issue just comment there first so I can assign you.

**Pull request closed without merging**
