### PR TITLE
redux features added for state management

### PR DESCRIPTION
**Pull request by nazrul7711**
hey @Chris5613  I have added redux for state management plz check.

### CODE REVIEW

**Comment by Chris5613** [comment]
@nazrul7711 Hey some code was added after you submitted your pull request, resolve the merge conflict then push it. 

Be careful not to delete anything from the merge conflict that is needed.

**Review by Chris5613 — APPROVED** [review]

**Comment by Chris5613** [comment]
@nazrul7711 Please fix merge conflicts and delete all comments.

**Comment by Chris5613** [comment]
4956434e397c53354ac77d4f4df9e253

I noticed a small name difference today, you forgot to rename csgo into league so it was messing up all the league videos but no worries I fixed it.

**Comment by nazrul7711** [comment]
Ok thanks

**Pull request merged**
