### PR TITLE
Username moderation

### PR DESCRIPTION
**Pull request by loshjarson**
Backend now fully handles username moderation including duplicate and inappropriate usernames. 

 *I was not able to test the profanity filter as I do not have a development environment setup for backend*

Referencing Issue #56

### CODE REVIEW

**Comment by Chris5613** [comment]
Looks good to me. I'll merge and test it

**Comment by Chris5613** [comment]
@loshjarson apart from some minor changes the backend is pretty good. All I changed is var filter to let filter since var isn't really used anymore. 

Front End you delete 
```javascript
    if (userId && storedUsername !== 'Guest') {
      saveUser(storedUsername, storedScore);
    }
```
but that is needed to save the user to the database for the leaderboard part.

Also for the if statement the username wasn't getting saved into cookies since you had it in an else so instead of that, I just had it after the if. 

```javascript
    const checkUsername = async () => {
      if (newUsername === null || newUsername === '') {
        newUsername = prompt('Please enter a new username');
        checkUsername();
      } 
      const newUser = await saveUser(newUsername, score);
      if(newUser.error){
        newUsername = prompt(newUser.error)
        checkUsername()
      }
      Cookies.set('username', newUsername, { secure: true });
      Cookies.set('isUsernameChanged', true, { secure: true });
      setUsername(Cookies.get('username'));
      setIsUsernameChanged(true);       
    };
```

Other than that, It works pretty well I tested a couple of bad/racist words and it all came back as an error so great work!

**Comment by loshjarson** [comment]
`if (userId && storedUsername !== 'Guest') {
      saveUser(storedUsername, storedScore);
    }`

This seemed unnecessary, since saveUser() is already being called when a username is created. And it was causing the request to be fired whenever you open the settings page along with sending two requests when adding a username.

**Comment by Chris5613** [comment]
ahh you're right I didn't see this

```javascript
      const newUser = await saveUser(newUsername, score);
```

I will make the change.

**Pull request merged**
