### PR TITLE
Navbar changed

### PR DESCRIPTION
**Pull request by ynzulak**
I improved a Navbar with media queries and an animation. I only worked for 768px media queries here. I'm pulling request with a question. what do you think about making media queries by me? I can add some burger menu to it. Or even i can work for whole site. What do you think about that? Have a nice evening 😁.

### CODE REVIEW

**Review by Chris5613 — CHANGES_REQUESTED** [review]
If you can add a hamburger menu that would be great, I will test your code when I'm free

**Comment by Chris5613** [comment]
@ynzulak you're going to need to make it so it fits on a moblie screen other than that it looks pretty good

**Review by Chris5613 — CHANGES_REQUESTED** [review]
Are you testing the code before you submit? the hamburger menu does not show.

**Comment by ynzulak** [comment]
I added a working burgermenu but without animations because i dont have enough time
Is it good?

**Review by Chris5613 — APPROVED** [review]
Looks good enough

**Pull request merged**
